//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace remoteValidation2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class tblUser
    {
        public int Id { get; set; }
        [Required]
        public string FullName { get; set; }
        [Required]
        [Remote("IsUserNameAvailable", "tblUsers", ErrorMessage = "UserName already exists....")]
        public string UserName { get; set; }
        [Required]
        public string Password { get; set; }
    }
}
